sudo: required
dist: focal

language: cpp

addons:
  apt:
    update: true
    packages: [libeigen3-dev, libglew-dev, libc++-dev, libwayland-dev, libxkbcommon-dev, wayland-protocols, libegl1-mesa-dev, meson, libcairo2-dev, libdbus-1-dev]
  homebrew:
    update: true
    packages: [eigen, glew]

matrix:
  include:
    - os: linux
      compiler: gcc
      env: PARALLEL_BUILD="-- -j 8"
    - os: linux
      env:
        - PARALLEL_BUILD="-- -j 8"
        - CMAKE_OPTIONS="-DDISPLAY_WAYLAND=ON -DDISPLAY_X11=OFF"
    - os: linux
      compiler: clang
      env: PARALLEL_BUILD="-- -j 8"
    - os: osx
      env: PARALLEL_BUILD="-- -j 8"
    - os: windows
      env: PARALLEL_BUILD="--parallel 8"

script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release $CMAKE_OPTIONS ..
  - cmake --build . $PARALLEL_BUILD
